#!/bin/sh
#
# 'run' bash script

./kernel.sh
./test.sh


if [ "$1" == "clean" ]; then
    rm -r build
fi
if [ -d "build" ]; then
    echo 
else
    mkdir build
fi
FILE=./build/Makefile
if [ -e "$FILE" ]; then
    cd build
    make -j$(nproc)
    cd ..
    if [ "$1" == "build" ]; then
        echo "done"
    else
        # if [ $? -eq 0 ]; then
        ./build/main
        # fi
    fi
else
    cd build
    cmake ..
    make -j$(nproc)
    cd ..
    if [ "$1" == "build" ]; then
        echo "done"
    else
        # if [ $? -eq 0 ]; then
        ./build/main
        # fi
    fi
fi

